version: '3.0'
services:
  library-db:
    container_name: library-db
    image: postgres
    restart: always
    volumes:
      - ./data-storage:/var/lib/postgresql/data
    ports:
      - "9000:5432"
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: 123456

  
  python-app:
    container_name: python-app
    image: python:3.11

    working_dir: /usr/src/app
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt &&
               python3 manage.py makemigrations &&
               python3 manage.py migrate &&
                python3 manage.py createadmin &&
               python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - library-db

