# Generated by Django 5.2.1 on 2025-05-27 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loanmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='borrow',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
