# Generated by Django 5.2.1 on 2025-05-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_loanmodel_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='page',
            new_name='page_count',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='count',
        ),
    ]
